name: dei_marc
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.5.0-266.0.dev <4.0.0'

# add dependencies here
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider:
  shared_preferences: ^2.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  
  
  
  
  flutter_lints: ^4.0.0
flutter:
  assets:
    - assets/data/ 
    - assets/data/books/
    - assets/data/categories/
    - assets/data/subcategories/
    - assets/data/contents/book1/
    - assets/data/contents/book2/
    - assets/data/contents/book3/
    - assets/images/placeholder.png
    - assets/images/book_covers/
    - assets/images/book1/
    - assets/images/book2/
  
  uses-material-design: true
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
